# https://taskfile.dev

version: '3'

vars:
  GREETING: Welcome to Wits!

tasks:
  default:
    cmds:
      - air
    silent: true
  install-godoc:
    internal: true
    cmds:
      - go install golang.org/x/tools/cmd/godoc@latest
    silent: true
  install-gotests:
    internal: true
    cmds:
      - go install github.com/cweill/gotests/gotests@latest
    silent: true
  install-air:
    internal: true
    cmds:
      - go install github.com/cosmtrek/air@latest
  install:
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/cosmtrek/air@latest
      - go install github.com/cweill/gotests/gotests@latest
      - go install golang.org/x/tools/cmd/godoc@latest
      - go get ./...
      - go mod vendor
      - go mod tidy
      - go mod download
      - npm install -D tailwindcss
      - npm install -D daisyui@latest
  clean:
    cmds:
      - cmd: rm ./bin/wits{{exeExt}}
        ignore_error: true
      - cmd: rm coverage.html
        ignore_error: true
      - cmd: rm coverage.out
        ignore_error: true
  build:
    deps: [templ-generate, tailwind-build]
    cmds:
      - go build -v -o ./bin/wits{{exeExt}} ./cmd/server.go
    sources:
      - '**/*.go'
    generates:
      - app{{exeExt}}
    method: timestamp
  doc:
    deps: [install-godoc]
    cmds:
      - godoc
  tailwind-build:
    internal: true
    cmds:
      - npx tailwindcss -i ./pkg/view/css/app.css -o ./public/css/styles.css --minify
  tailwind-watch:
    cmds:
      - npx tailwindcss -i ./pkg/view/css/app.css -o ./public/css/styles.css --watch
  templ-generate:
    internal: true
    cmds:
      - templ generate
  templ-generate-watch:
    cmds:
      - templ generate -watch -proxy http:=//localhost:3000
  test:
    deps: [install-gotests]
    cmds:
      - go test -race -v ./... -coverprofile coverage.out
    sources:
      - '**/*.go'
    generates:
      - coverage.out
    method: timestamp
  test-ci:
    deps: [install-gotests]
    cmds:
      - go test -race -v ./... -coverprofile coverage.out -covermode=atomic
      - bash <(curl -s https://codecov.io/bash)
    sources:
      - '**/*.go'
    generates:
      - coverage.out
    method: timestamp
  cover:
    deps: [test]
    cmds:
      - go tool cover -html coverage.out -o coverage.html
    sources:
      - coverage.out
    generates:
      - coverage.html
    method: timestamp
  show-cover:
    deps: [cover]
    cmds:
      - open coverage.html
  vet:
    cmds:
      - go vet ./...
