# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Install Dependencies
        run: task install

      - name: Build
        run: task build

      - name: Test
        run: task test-ci

      - name: Vet
        run: task vet

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: TheDonDope/wits
